@startuml
!define table(x) class x << (T,#FFAAAA) >>
!define factT(x) class x << (F,#DC504F) fact >>
!define dimT(x) class x << (D,#3E93B5) dim >>
!define softDimT(x) class x << (D,#3E93B5) softDim >>
!define primary_key(x) <b><font size="14" color="#4041A4">x</font></b>
!define foreign_key(x) <b><font size="12" color="#6666FF">x</font></b>
!define link(t1,c1,t2,c2) t1 c1 -- c2 t2
hide empty fields
hide stereotypes

skinparam class {
  BackgroundColor<<fact>> #FFF9F9
  BackgroundColor<<dim>> #EFF5F8
  BackgroundColor<<softDim>> #CDCDCD
  BorderColor<<fact>> #DC504F
  BorderColor<<dim>> #3E93B5
  BorderColor<<softDim>> #3E93B5
  ArrowColor #1078A1
}

package "Entity Level" as Entity <<Rect>>{
  factT("AccountMQ" as Acct) {
    primary_key(mdm_id: String)
    foreign_key(zip: String)
    primary_key(time_type)
    primary_key(time_value)
    --
    vials_3MG: Double
    vials_5MG: Double
    vials_norm: Double
    p_mdm_id: String
    p_zip: String
    tier: Integer
    sales_decile: Integer
    phy_cnt: Long
    claim_cnt: Double
    pat_cnt: Double
    claim_cnt_Avastin/Eylea/Lucentis: Double
    claim_cnt_DME/RVO/WAMD: Double
    claim_cnt_Avastin/Eylea/Lucentis_DME/RVO/WAMD: Double
    pat_cnt_Avastin/Eylea/Lucentis: Double
    pat_cnt_DME/RVO/WAMD: Double
    pat_cnt_Avastin/Eylea/Lucentis_DME/RVO/WAMD: Double
    rs_cnt: Double
    rs_prescribed_luc_cnt: Long
    nonrs_prescribed_luc_cnt: Long
    phy_cnt_hascall: Long
    phy_cnt_hascopay: Long
    phy_cnt_hassample: Long
    phy_cnt_hasspeaker: Long
    ***
  }

  factT("PhysicianMQ" as Phys) {
    primary_key(ame: String)
    foreign_key(zip: String)
    time_type: String //Month
    time_value: Int
    --
    claim_cnt: Double
    pat_cnt: Double
    claim_cnt_Avastin/Eylea/Lucentis: Double
    claim_cnt_DME/RVO/WAMD: Double
    claim_cnt_Avastin/Eylea/Lucentis_DME/RVO/WAMD: Double
    pat_cnt_Avastin/Eylea/Lucentis: Double
    pat_cnt_DME/RVO/WAMD: Double
    pat_cnt_Avastin/Eylea/Lucentis_DME/RVO/WAMD: Double
    luc_claims_decile: Integer
    market_claims_decile: Integer
    cnt_call: Double
    cnt_copay: Double
    cnt_sample: Double
    cnt_speaker: Double
    phy_ind_clmLucIncrs_cQpY: Integer
    phy_ind_clmEylIncrs_cQpY: Integer
    phy_ind_clmAvaIncrs_cQpY: Integer
    phy_ind_clmLucDecrs_cQpY: Integer
    phy_ind_clmEylDecrs_cQpY: Integer
    phy_ind_clmAvaDecrs_cQpY: Integer
    ***
  }

  factT("Static Patient" as Pati) {
    primary_key(zip: String)
    --
    patient_est_DME: Double
    patient_est_RVO: Double
    patient_est_WAMD: Double
    ***
  }
}

package "Geo Summaries" as GeoS <<Rect>>{

  factT("AcctSummaryByGeoMQ" as AcctGeo){
    primary_key(geo_type)
    primary_key(geo_value)
    primary_key(time_type)
    primary_key(time_value)
    --
    geo_cnt_AcctLucSaleTot: Double
    geo_cnt_ld_AcctLucSaleTot: Double
    geo_cnt_non_ld_AcctLucSaleTot: Double
    geo_cnt_ld_acct: Long
    geo_cnt_non_ld_acct: Long
    geo_cnt_acctPurchLuc_cQ: Long
    geo_cnt_acctHighSalDcl_cQ: Long
    geo_cnt_AcctLucSale_call: Double
    geo_cnt_AcctLucSale_copay: Double
    geo_cnt_AcctLucSale_sample: Double
    geo_cnt_AcctLucSale_speaker: Double
    geo_cnt_acctPrscrLuc_2012andUp: Long
    geo_alg_acctClmAvaGini_cQ: Double
    geo_alg_acctClmEylGini_cQ: Double
    geo_alg_acctClmLucGini_cQ: Double
    geo_alg_acctClmAvaGiniNZ_cQ: Double
    geo_alg_acctClmEylGiniNZ_cQ: Double
    geo_alg_acctClmLucGiniNZ_cQ: Double
    geo_alg_acctSalGini_cQ: Double
    geo_alg_acctSalGiniNZ_cQ: Double
    p_count_4up_tiers: Long
    geo_pct_p_4upAcct_cQ: Double
    geo_pct_4upAcct_cQ: Double
    geo_rto_acctPurchLuc_cQ_acctPrscrLuc_2012andUp: Double
    geo_rto_acctHighSalDcl_acctPurchLuc_cQ: Double
    geo_rto_acctHighSalDcl_cQ_acctPrscrLuc_2012andUp: Double
    geo_rto_vials_acctPurchLuc_cQ: Double
    geo_rto_AcctLucSale_call_cQ_AcctLucSaleTot: Double
    geo_rto_AcctLucSale_copay_cQ_AcctLucSaleTot: Double
    geo_rto_AcctLucSale_sample_cQ_AcctLucSaleTot: Double
    geo_rto_AcctLucSale_speaker_cQ_AcctLucSaleTot: Double
    ***
  }

  factT("PhysSummaryByGeoMQ" as PhysGeo){
    primary_key(geo_type)
    primary_key(geo_value)
    primary_key(time_type)
    primary_key(time_value)
    --
    geo_cnt_rsPhy_cQ: Long
    geo_alg_phyClmLucGini_cQ: Double
    geo_alg_phyClmAvaGini_cQ: Double
    geo_alg_phyClmEylGini_cQ: Double
    geo_alg_phyClmLucGiniNZ_cQ: Double
    geo_alg_phyClmAvaGiniNZ_cQ: Double
    geo_alg_phyClmEylGiniNZ_cQ: Double
    geo_cnt_phy_2012Q1to2014Q2: Long
    geo_cnt_phyPrscrLuc_2012Q1to2014Q2: Long
    geo_cnt_phys_cQ: Long
    geo_rto_rsPhy_phys_cQ: Double
    geo_rto_clmLuc_clmTot_cQ: Double
    geo_rto_rsClmLuc_rsClmTot_cQ: Double
    geo_rto_nonrsClmLuc_nonrsClmTot_cQ: Double
    geo_rto_phyPrscrLuc_phys_cQ: Double
    geo_rto_rsPhyPrscrLuc_rsPhy_cQ: Double
    geo_rto_nonrsPhyPrscrLuc_nonrsPhy_cQ: Double
    geo_rto_phyClm{Luc/Ava/Eyl}Incrs_cQpY_phys_cQ: Double
    geo_rto_phyClm{Luc/Ava/Eyl}Decrs_cQpY_phys_cQ: Double
    geo_rto_phyHighLucClmDcl_phys_cQ: Double
    geo_rto_phyHighMktClmDcl_phys_cQ: Double
    geo_pct_phyHaveCall_cQ: Double
    geo_pct_phyHaveCopay_cQ: Double
    geo_pct_phyHaveSample_cQ: Double
    geo_pct_phyHaveSpeaker_cQ: Double
    geo_rto_callPerPhy_cQ: Double
    geo_rto_callPerRs_cQ: Double
    geo_rto_callPerNonrs_cQ: Double
    geo_pct_phyHaveCall_cQ_prev_1_quarter: Double
    geo_pct_phyHaveCopay_cQ_prev_1_quarter: Double
    geo_pct_phyHaveSample_cQ_prev_1_quarter: Double
    geo_pct_phyHaveSpeaker_cQ_prev_1_quarter: Double
    ***
  }

  factT("MktShareProjMQ" as Share) {
    primary_key(geo_type)
    primary_key(geo_value)
    primary_key(time_type)
    primary_key(time_value)
    --
    is_confident: Boolean
    total_market_vials_est: Double
    vials_lucentis: Double
    share_lucentis: Double
    ***
  }

  factT("PatSummaryByGeoMQ" as PatGeo){
    primary_key(geo_type)
    primary_key(geo_value)
    primary_key(time_type)
    primary_key(time_value)
    --
    geo_est_popPatCnt_sta: Double
    geo_pct_positive_favorability: Double
    geo_est_treatedPat_cQ: Double
    geo_rto_treatedPat_cQ_popPatCnt_sta: Double
    geo_rto_shaVials_shaPat_cQ: Double
    ***
  }
}

@enduml
