@startuml
!define table(x) class x << (T,#FFAAAA) >>
!define factT(x) class x << (F,#DC504F) fact >>
!define dimT(x) class x << (D,#3E93B5) dim >>
!define softDimT(x) class x << (D,#3E93B5) softDim >>
!define primary_key(x) <b><font size="14" color="#4041A4">x</font></b>
!define foreign_key(x) <b><font size="12" color="#6666FF">x</font></b>
!define link(t1,c1,t2,c2) t1 c1 -- c2 t2
hide empty fields
hide stereotypes

skinparam class {
  BackgroundColor<<fact>> #FFF9F9
  BackgroundColor<<dim>> #EFF5F8
  BackgroundColor<<softDim>> #CDCDCD
  BorderColor<<fact>> #DC504F
  BorderColor<<dim>> #3E93B5
  BorderColor<<softDim>> #3E93B5
  ArrowColor #1078A1
}


package "External" as External <<Rect>>{
  factT("Cms NPI master") {
    primary_key(npi)
    ---
    ***
  }
  factT("Cms Reimbursement") {
    foreign_key(npi)
    foreign_key(proc_code)
    ---
    ***
  }
  factT("Cms Referal") {
    foreign_key(referer_npi)
    foreign_key(referee_npi)
    ---
    ***
  }
  package "Clinial Trial DB" as Trial <<Rect>>{
    factT("Table1")
    factT("Table2")
  }
}

@enduml
