@startuml
!define table(x) class x << (T,#FFAAAA) >>
!define factT(x) class x << (F,#DC504F) fact >>
!define dimT(x) class x << (D,#3E93B5) dim >>
!define softDimT(x) class x << (D,#3E93B5) softDim >>
!define primary_key(x) <b><font size="14" color="#4041A4">x</font></b>
!define foreign_key(x) <b><font size="12" color="#6666FF">x</font></b>
!define link(t1,c1,t2,c2) t1 c1 -- c2 t2
hide empty fields
hide stereotypes

skinparam class {
  BackgroundColor<<fact>> #FFF9F9
  BackgroundColor<<dim>> #EFF5F8
  BackgroundColor<<softDim>> #CDCDCD
  BorderColor<<fact>> #DC504F
  BorderColor<<dim>> #3E93B5
  BorderColor<<softDim>> #3E93B5
  ArrowColor #1078A1
}

package "Sales / Panel data" as Sales <<Rect>>{
  factT(SAP) {
    'Monthly Sales Outs to Prescriber and HCO end customers
    foreign_key(sales_rep_id)
    foreign_key(mdm_id) //Physicians and Account
    month
  }
  factT(WSR) {
    'Weekly Shipment and Reimbursement Specialty Pharmacy data from key Genentech Specialty Distributors
    primary_key(trx_id)
    foreign_key(spec_dist_id)
    foreign_key(product_id)
    week
  }
  factT(DDD-MD){
    'Monthly HCO Outlet-level sales data (DDD-MD deliverable)
    foreign_key(account_id)
    foreign_key(product_id)
    month
    ---
    strength
    sales
  }
  factT(Xponent) {
    'Monthly Prescriber-level sales data
    foreign_key(md_id) // Physicians
    foreign_key(product_id)
    month
    ---
    strength
    sales
  }
}

@enduml
