@startuml
!define table(x) class x << (T,#FFAAAA) >>
!define primary_key(x) <u><font size="14" color="blue">x</font></u>
!define foreign_key(x) <font size="12" color="Green">x</font>
!define link(t1,c1,t2,c2) t1 c1 -- c2 t2
!define linkTo(t1,c1,t2) t1 c1 --> t2

table(apac) {
year: Integer
primary_key(patid: String)
gender: String
agegrp: String
foreign_key(race: Integer)
foreign_key(ethnicity: Integer)
language: Integer
metro: Integer
paid: Double
patpaid: Double
foreign_key(payer: String)
foreign_key(pos: Integer)
urban: Integer
dx1: Integer
px1: String
foreign_key(proccode: String)
foreign_key(status: String)
los: Integer
foreign_key(ecode: String)
foreign_key(hcg: String)
msdrg: String
quarter: Integer
}


@enduml