@startuml
hide empty methods
hide empty fields
hide circle

class Zip
class Zip3
class County
class State
class HSA
class HRR
class Territory
class Division

Zip --* Zip3
Zip --* HSA
Zip --* Territory

Zip ..* County
Zip ..* State
County --* State
Zip3 ..* State

HSA --* HRR
Territory --* Division

@enduml

